### ISSUE TITLE
Online engine down for some days.

### ISSUE THREAD

**Issue by ghost** [MaLeLabTs/RegexGenerator#13]
regex.inginf.units.it has been down now for a couple of days. Will it be coming back?

**Comment by adelorenz** [comment]
Hi Runisco, the site is online and working. Apparently it worked all week.
Try again if you are able to reach it, otherwise let me know!
We are planning to move our infrastructure in the coming weeks to offer greater reliability.

**Comment by ghost** [comment]
_"The connection has timed out
The server at regex.inginf.units.it is taking too long to respond."_
https://downforeveryoneorjustme.com/regex.inginf.units.it

**Comment by adelorenz** [comment]
yes, apparently there is a problem
we are investigating

**Comment by adelorenz** [comment]
We discovered a problem with the firewall policies. Now it's solved. Thank you for for letting us know.
