### ISSUE TITLE
Can this do substitutions?

### ISSUE THREAD

**Issue by KrishnaPG** [MaLeLabTs/RegexGenerator#3]
How easy / complex is it to support 'substitutions'?

**Comment by ftarlao** [comment]
Do you mean something like [this](https://43ec4ed0-a-62cb3a1a-s-sites.googlegroups.com/site/machinelearningts/publications/international-conference-publications/automaticstringreplacebyexamples/2013-GECCO-AutomaticStringReplaceByExamples.pdf?attachauth=ANoY7crTAHMzfYZu59ueDflA56xN-wYzT-RfzrD249WhNuq7H0viCEKuq6Qp06qCu09opJP6u2DtzPzm9YzWxqpkYQU7_9sbOgr31EKdj0ec9Y8RELPkWj31zZ5v0mQl4e0zH6c1GosXGuqHoX0U9_AYLcIqqvQVmLVP0B_TdEICaQQx5BEjytJyH_7jsnWKMOfPpgJEHqABrvGcBON3rDH7umO1-F1RAUbFHU-PlsrOaELxBohzGLLSHXojcpvjcqNfgNSCVwvYBy9digyK4y_3npea5q_BZK7oHVmEwXrutV1ZWtgLzUE0J4yFC1idMYsPH4U32YetAG8vXRsAlm34shotqDEx-UXNiKr-aHhSnYpLY1g-qVbYttIVIawOkPYi9lEQz5W1&attredirects=0)?

**Comment by KrishnaPG** [comment]
Yes, exactly.

Essentially, given a set of mappings (say, as key-value json pairs), the tool should generate the substitution rules.

For example:

```
{
  'a'    :  'A',
  'ba'  :  'B',
  'b'   :  'b'
}
```

Left side (keys) should be captured and replaced with right side values.

Note the context-dependency for the `ba` vs `a` and `ba` vs `b`.

Looking for some tool that can do this (in javascript, so that it works on web also). Any lexer/parser tools that lets us design and maintain such mapping rules is also helpful.

**Comment by ftarlao** [comment]
I'm sorry, we are not aware of a working solution for the problem you described. 
At the moment, we experimented with few variants of the cited article with no conclusive results.

**Comment by KrishnaPG** [comment]
Not a problem. Thank you.
