### ISSUE TITLE
example config file and input

### ISSUE THREAD

**Issue by dportabella** [MaLeLabTs/RegexGenerator#6]
I try to run the software (without GUI) as follows:

```
$ git clone git@github.com:MaLeLabTs/RegexGenerator.git
$ cd RegexGenerator
$ cd "Random Regex Turtle"
$ ant -Dplatforms.JDK_1.7.home $JAVA_HOME jar
$ java -jar ./dist/Random_Regex_Turtle.jar 
Usage: java -jar "Random_Regex_Turtle.jar" configFileName [startGui]
```
Can you please provide an example config file and input (without using the GUI)?

**Comment by adelorenz** [comment]
You can find the detailed description of how to use the console [here](https://github.com/MaLeLabTs/RegexGenerator/wiki/ConsoleRegexTurtle-(Console-Application)).

In the repository there is also a test dataset. Take a look [here](https://github.com/MaLeLabTs/RegexGenerator/tree/master/ConsoleRegexTurtle/testdataset).

**Comment by dportabella** [comment]
I see, thanks.
In case others are interested:

```
git clone git@github.com:MaLeLabTs/RegexGenerator.git
cd RegexGenerator
cd ConsoleRegexTurtle
ant -Dplatforms.JDK_1.7.home $JAVA_HOME jar
java -jar ./dist/ConsoleRegexTurtle.jar -t 4 -p 500 -g 1000 -e 20.0 -c "interesting evolution" -x true -d ./testdataset/reduced.json -o ./outputfolder/
cat ./outputfolder/results-20170214021423.json
```
